add theme Support
emeks-studio/antd-custom-theme-generator pull request #4
Opened 2020-10-06 23:48 UTC by mehdiraized

plz add version

2020-10-08 10:58 UTC, mehdiraized commented
@mk-emeks plz check

2020-10-09 11:57 UTC, randomeduc commented on README.md
> +`You Can Change with theme Parametr`
There's a little typo in Parametr and I think that is not necessary to capitalize each word.

It would be nice to reference to the antd theme folder so the user know where to find the respective .less file (https://github.com/ant-design/ant-design/tree/master/components/style/themes). Maybe rephrase the previous paragraph, what do you think?

2020-10-10 06:27 UTC, mehdiraized commented on README.md
> +`You Can Change with theme Parametr`
My English is not good, please change it yourself

2020-10-11 15:28 UTC, mk-emeks requested changes

2020-10-11 15:28 UTC, mk-emeks commented on README.md
> +`You Can Change with theme Parametr`
```suggestion
> Also, you could use `[theme]` parameter in order to target to a different theme such as `dark` or `compact` (To check all available options, please inspect this folder: https://github.com/ant-design/ant-design/tree/master/components/style/themes).
```

2020-10-11 15:28 UTC, mk-emeks commented on README.md
> +> - theme = "defualt" You can use dark or compact
```suggestion
> - theme = "default"
```

2020-10-11 15:30 UTC, mk-emeks commented on README.md
> +> - theme = "defualt" You can use dark or compact
Also notice that few lines above

```
 $ generate-theme [verbose] [customThemeFilePath] [generatedThemeFilePath] [antdLibraryPath]
```

should be now:
```
 $ generate-theme [verbose] [customThemeFilePath] [generatedThemeFilePath] [antdLibraryPath] [theme]
```

2020-10-11 15:31 UTC, mk-emeks commented on README.md
> +`You Can Change with theme Parametr`
@mehdiraized I suggested the expected changes so you could apply them in your branch =)

2020-10-11 23:11 UTC, merged

2020-10-12 00:46 UTC, randomeduc commented
@mehdiraized `v0.1.5` with theme support is out. Thanks for your contribution! :smiley: